env:
  global:
    secure: "U70BMKXb/GfxXY+JrzybhfORD0Xvovxee68N9TRVmR1AfOflbSsiWybxhTUzayJ1THKxrVzrMWRcSILbJKjCEyJFFrHIV0jdOqAzlGw98zQZKm5CFcHIlKF1u4a2rnjVsFcLYT6gZ4hrcQnC4IEwk4BfEfNHk+OEOP8piTSfwBUXmGwPwpSaaIn2cBRpAxYqjdChvGVxs7NmS4/d8iN8m9BJIqKLFry00PoJEcq9RmrS0fi2ONgKmqR7Hho5GLwWvqliN75tA79p5xzKEAKHzBWNNRF2gE/P7yKXw4me5B5svmL1EIsjbtntRpEWWkQPZEmcomczi7vQapha42AUMFNXfeVw0DriH7lprKlDy6DPPElMDjhWnjn/p5R4uwk7hoUOkwGLi1iBRwCr/y8J9MqGyGIPieFp7jPnKfc+nHi+Oqhhm5cdk3dUjQPsh7apENQ/OdM/3pHZJ5m73yV7JwWnZE8KB+2MQ2kh2vUDyOGeUp28csZUFNcG7hX1XTOSBUjHJhhy0YeyQ66RonCVBGyPS3DU0yCfAdjIajgaOjYuiwlrmZh2muOHChoKgYuMf8MkuIhtKwPXMIyhdvP+0DlCB2kbN+If3M057HhLodqUbDegw5GjJCm/D1dTv3Z41xZcKtk9SrIk3svVr/I9joGniJvCIE++9RT0k/vsDHs="
matrix:
  fast_finish: true
  include:
    - language: python
      python: 2.7
      os: linux
      dist: trusty
    - language: python
      python: 3.5
      os: linux
      dist: trusty
    - language: generic
      env: PY=2
      os: osx
    - language: generic
      env: PY=3
      os: osx
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ "${DOCKER_IMAGE}" == "" ]; then
      sudo apt-get update;
      sudo apt-get -y install libsdl2-dev libsdl2-mixer-dev python-dev;
      mkdir ~/ffmpeg_sources;
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/ffmpeg_build/lib;

      sudo apt-get -y install yasm;
      cd ~/ffmpeg_sources;
      wget http://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz;
      tar xzf yasm-1.3.0.tar.gz;
      cd yasm-1.3.0;
      ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin";
      make;
      make install;
      make distclean;

      sudo apt-get -y install nasm;
      cd /home/cpl/python/ffmpeg_sources;
      wget http://www.nasm.us/pub/nasm/releasebuilds/2.13.01/nasm-2.13.01.tar.xz;
      tar xf nasm-2.13.01.tar.xz;
      cd nasm-2.13.01;
      ./configure --prefix="/home/cpl/python/ffmpeg_build" --bindir="/home/cpl/python/ffmpeg_build/bin";
      make;
      make install;
      make distclean;

      sudo apt-get -y install libx264-dev;
      cd ~/ffmpeg_sources;
      wget http://download.videolan.org/pub/x264/snapshots/last_x264.tar.bz2;
      tar xjf last_x264.tar.bz2;
      cd x264-snapshot*;
      PATH="$HOME/ffmpeg_build/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/ffmpeg_build/bin" --enable-shared --extra-cflags="-fPIC";
      PATH="$HOME/ffmpeg_build/bin:$PATH" make;
      make install;
      make distclean;

      sudo apt-get -y install libmp3lame-dev;
      sudo apt-get -y install nasm;
      cd ~/ffmpeg_sources;
      wget http://downloads.sourceforge.net/project/lame/lame/3.99/lame-3.99.5.tar.gz;
      tar xzf lame-3.99.5.tar.gz;
      cd lame-3.99.5;
      ./configure --prefix="$HOME/ffmpeg_build" --enable-nasm --enable-shared;
      make;
      make install;
      make distclean;

      sudo apt-get -y install libass-dev libfreetype6-dev libtheora-dev libvorbis-dev;
      cd ~/ffmpeg_sources;
      wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2;
      tar xjf ffmpeg-snapshot.tar.bz2;
      cd ffmpeg;
      PATH="$HOME/ffmpeg_build/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --extra-cflags="-I$HOME/ffmpeg_build/include -fPIC" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --bindir="$HOME/ffmpeg_build/bin" --enable-gpl --enable-libass --enable-libfreetype --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-shared;
      PATH="$HOME/ffmpeg_build/bin:$PATH" make;
      make install;
      make distclean;
      hash -r;

      pip install --upgrade cython nose;
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      brew update;
      brew install sdl2;
      brew install sdl2_mixer;
      brew install ffmpeg --with-freetype --with-libass --with-libvorbis --with-libvpx --with-libmp3lame --with-x264 --with-libtheora;
      if [ "${PY}" == "3" ]; then
         curl -O -L https://www.python.org/ftp/python/3.5.1/python-3.5.1-macosx10.6.pkg;
         sudo installer -package python-3.5.1-macosx10.6.pkg -target /;
         pip3 install --upgrade --user cython nose;
      else
         pip install --upgrade --user cython nose;
      fi;
    fi;

before_script:
    cd "$TRAVIS_BUILD_DIR";
    export PYTHONPATH=$PYTHONPATH:$(pwd);
    export USE_SDL2_MIXER=1;

script:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ] && [ "${DOCKER_IMAGE}" == "" ]; then
        PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" make;
        make test;
    fi;
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if [ "${PY}" == "3" ]; then
         python3 setup.py build_ext --inplace;
         python3 -m nose.core ffpyplayer/tests;
      else
         make;
         make test;
      fi;
    fi;
  - if [ "${DOCKER_IMAGE}" != "" ]; then
      mkdir wheelhouse;
      docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.travis/build-wheels.sh;
      tar -czvf ffpyplayer-wheels.tar.gz $(find wheelhouse/ -type f -name '*manylinux*');
      ls wheelhouse/;
      rm "wheelhouse/*.whl";
    fi;
deploy:
  provider: s3
  access_key_id: "AKIAI6W6F6NSTY3TAU6Q"
  bucket: "ffpyplayer-wheels"
  skip_cleanup: true
  region: us-east-1
  local_dir: wheelhouse
  upload-dir: ffpyplayer
  on:
    condition: "$DOCKER_IMAGE"
    all_branches: true
